spring:
    thymeleaf:
        cache: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yummy?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

weather:
    uri: "http://wthrcdn.etouch.cn/weather_mini?"
    redisTimeOut: 1800
    jobTime: 1800

redis:
#    database: 0
    host: localhost
    port: 6379  
#    password:   
    # 连接池最大连接数（使用负值表示没有限制）  
    pool.max-active: 8  
    # 连接池最大阻塞等待时间（使用负值表示没有限制）  
    pool.max-wait: -1  
    # 连接池中的最大空闲连接  
    pool.max-idle: 8  
    # 连接池中的最小空闲连接  
    pool.min-idle: 0  
    # 连接超时时间（毫秒）  
    timeout: 0
    
# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.zhefan.yummy.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
   #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
   #驼峰下划线转换
    db-column-underline: true
   #刷新mapper 调试神器
    refresh-mapper: true
   #数据库大写下划线转换
    capital-mode: false

logging:
    level:
        com.zhefan.yummy.dao: debug
        