######################## 容器 ########################
server:
  port: 80
  context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  
######################## Spring 全局设置 ########################
spring:
  application:
    name: yummy
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.248.96:3306/yummy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: y123456y
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    mode: LEGACYHTML5
  redis:
    #集群模式
    #cluster:
    #  nodes:
    #    - 39.XXX.XX.69:6661
    #    - 39.XXX.XX.69:6662
    #    - 39.XXX.XX.69:6663
    #    - 39.XXX.XX.69:6664
    #    - 39.XXX.XX.69:6665
    #    - 39.XXX.XX.69:6666
    #单机模式
    database: 0
    host: 47.107.248.96
    port: 6379  
    password: r12345y
    # 连接池最大连接数（使用负值表示没有限制）  
    pool.max-active: 8  
    # 连接池最大阻塞等待时间（使用负值表示没有限制）  
    pool.max-wait: -1  
    # 连接池中的最大空闲连接  
    pool.max-idle: 8  
    # 连接池中的最小空闲连接  
    pool.min-idle: 0  
    # 连接超时时间（毫秒）  
    timeout: 0
  jmx:
    default-domain: web80
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.qq.com
    username: reverienight@foxmail.com
    password: Frandre?0019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    
redisSession:
  cookieName: JSESSIONID
  cookiePath: /
  domainName: huzhenquan.com

######################## 日志 ########################
logging:
  pattern: 
    console: "%d - loooooooooooooog - %msg%n"
#  path: D:/log/
  file: log/shell.log
  level: 
    com.zhefan.yummy: debug
  

#debug: true

######################## mybatis-plus ########################
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhefan.yummy.entity
  global-config:
   #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
   #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
   #驼峰下划线转换
    db-column-underline: true
   #刷新mapper 调试神器
    refresh-mapper: true
   #数据库大写下划线转换
    capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

######################## socket ########################
#wss:
#  server:
#    port: 8888
#    host: localhost

socket:
  server:
    host: 47.107.248.96
    port: 8888
    
file:
  url:
#    upload: http://47.107.248.96:8111/file/uploadimg
#    change: http://47.107.248.96:8111/file/saveimg
#    del: http://47.107.248.96:8111/file/delimg
    upload: http://localhost:8111/file/uploadimg
    change: http://localhost:8111/file/saveimg
    del: http://localhost:8111/file/delimg

wx:
  appid: wxf8f1d3e7106c154d
  appsecrret: test


